{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "90e70412-3d46-4dc9-8ed9-4b8aec4cdf5e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "对手广告费分析：\n",
      "  历史平均：17.7\n",
      "  历史最高：20\n",
      "  建议本轮广告费区间：15.9 ~ 21.2\n",
      "\n",
      "=============================================\n",
      "第 1 轮财务状态\n",
      "=============================================\n",
      "  现金: 100\n",
      "  固定资产: 50\n",
      "  库存: 0\n",
      "  贷款: 0\n",
      "  所有者权益: 100\n",
      "  研发进度: {'P1': '完成', 'P2': '未开始'}\n",
      "  广告费: 0\n",
      "  生产线数量: 1\n",
      "  每季度固定支出: 10\n",
      "=============================================\n",
      "\n",
      "\n",
      "现金流预警：\n",
      "  当前现金：100\n",
      "  每季度支出（含利息）：10.0\n",
      "  若拿不到订单，还能撑：10 个季度\n",
      "AI正在分析，请稍候...\n",
      "\n",
      "AI建议：\n",
      "\n",
      "### 1. **广告费建议金额及理由**  \n",
      "**建议金额：30**  \n",
      "**理由**：  \n",
      "- 市场需求旺盛但竞争对手加大广告投入，需抢占市场份额。  \n",
      "- 原材料价格上涨10%会压缩利润空间，需通过广告费提升销量以抵消成本压力。  \n",
      "- 广告费投入需平衡短期收益与现金流风险。当前现金100，每季度固定支出10，贷款利息风险高，建议将广告费控制在**30**（占现金流的30%），既能快速扩大市场影响力，又不会过度消耗现金流。  \n",
      "\n",
      "---\n",
      "\n",
      "### 2. **是否贷款，贷多少**  \n",
      "**建议：不贷款**  \n",
      "**理由**：  \n",
      "- 贷款需支付利息（规则未明确利率，但存在风险），可能侵蚀所有者权益。  \n",
      "- 当前现金流可支撑10个季度，无需额外融资。  \n",
      "- 若未来需扩大产能或研发，可优先通过提升销量和利润积累资金，避免债务风险。  \n",
      "\n",
      "---\n",
      "\n",
      "### 3. **生产线调整建议**  \n",
      "**建议：暂不调整**  \n",
      "**理由**：  \n",
      "- 当前生产线数量为1，市场需求旺盛，需优先通过广告费提升销量以充分利用现有产能。  \n",
      "- 原材料价格上涨可能推高生产成本，若盲目扩建生产线会进一步增加固定成本压力。  \n",
      "- 若后续季度销量持续增长且现金流充足，可考虑新增生产线。  \n",
      "\n",
      "---\n",
      "\n",
      "### 4. **研发投入建议**  \n",
      "**建议：投入P2研发（金额待定）**  \n",
      "**理由**：  \n",
      "- 研发进度P1已完成，P2是关键突破点。若P2能带来技术优势（如降低成本或提升产品竞争力），需尽早投入。  \n",
      "- 当前所有者权益为100，可考虑投入**10-20**（占现金流的10%-20%）启动P2研发，但需结合广告费预算调整。  \n",
      "- 若研发资金紧张，可优先通过广告费提升销量，待现金流稳定后再投入研发。  \n",
      "\n",
      "---\n",
      "\n",
      "### 5. **本轮最优先事项**  \n",
      "**最优先事项：通过广告费抢占市场，同时控制成本**  \n",
      "**具体行动**：  \n",
      "1. **广告费投入30**，快速扩大市场份额以应对竞争对手。  \n",
      "2. **不贷款**，保持现金流灵活性。  \n",
      "3. **暂不调整生产线**，聚焦广告和销售。  \n",
      "4. **预留部分资金（如20）用于后续研发**，为长期竞争力做准备。  \n",
      "\n",
      "---\n",
      "\n",
      "### **核心策略总结**  \n",
      "- **短期**：以广告费为核心，扩大销量抵消原材料涨价压力。  \n",
      "- **中期**：通过销量增长积累资金，为后续研发和产能扩张铺路。  \n",
      "- **长期**：在确保现金流安全的前提下，逐步推进研发和产能升级，提升所有者权益。\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "import json\n",
    "import base64\n",
    "\n",
    "# ========== 核心 Agent ==========\n",
    "class ERPAgent:\n",
    "    def __init__(self):\n",
    "        self.round = 1\n",
    "        self.history = []\n",
    "        self.competitor_history = []  # 记录对手广告费\n",
    "        self.data = {\n",
    "            \"现金\": 100,\n",
    "            \"固定资产\": 50,\n",
    "            \"库存\": 0,\n",
    "            \"贷款\": 0,\n",
    "            \"所有者权益\": 100,\n",
    "            \"研发进度\": {\"P1\": \"完成\", \"P2\": \"未开始\"},\n",
    "            \"广告费\": 0,\n",
    "            \"生产线数量\": 1,\n",
    "            \"每季度固定支出\": 10\n",
    "        }\n",
    "\n",
    "    def calculate_equity(self):\n",
    "        equity = (self.data[\"现金\"] + self.data[\"固定资产\"]\n",
    "                  + self.data[\"库存\"] - self.data[\"贷款\"])\n",
    "        self.data[\"所有者权益\"] = equity\n",
    "        return equity\n",
    "\n",
    "    def update_data(self, updates: dict):\n",
    "        self.data.update(updates)\n",
    "        self.calculate_equity()\n",
    "        print(\"数据已更新，当前所有者权益：\" + str(self.data[\"所有者权益\"]))\n",
    "\n",
    "    def show_status(self):\n",
    "        print(\"\\n\" + \"=\"*45)\n",
    "        print(\"第 \" + str(self.round) + \" 轮财务状态\")\n",
    "        print(\"=\"*45)\n",
    "        for k, v in self.data.items():\n",
    "            print(\"  \" + str(k) + \": \" + str(v))\n",
    "        print(\"=\"*45 + \"\\n\")\n",
    "\n",
    "    # ===== 功能1：现金流死线预测 =====\n",
    "    def cash_flow_deadline(self):\n",
    "        cash = self.data[\"现金\"]\n",
    "        fixed_cost = self.data[\"每季度固定支出\"]\n",
    "        loan = self.data[\"贷款\"]\n",
    "        loan_interest = loan * 0.05  # 假设5%利息\n",
    "        total_cost_per_round = fixed_cost + loan_interest\n",
    "        if total_cost_per_round <= 0:\n",
    "            seasons = 999\n",
    "        else:\n",
    "            seasons = int(cash / total_cost_per_round)\n",
    "        print(\"\\n现金流预警：\")\n",
    "        print(\"  当前现金：\" + str(cash))\n",
    "        print(\"  每季度支出（含利息）：\" + str(round(total_cost_per_round, 2)))\n",
    "        print(\"  若拿不到订单，还能撑：\" + str(seasons) + \" 个季度\")\n",
    "        if seasons <= 2:\n",
    "            print(\"  !!!高危警告：现金流紧张，谨慎贷款和广告!!!\")\n",
    "        return seasons\n",
    "\n",
    "    # ===== 功能2：竞标压力分析 =====\n",
    "    def competitor_analysis(self, competitor_ads: list):\n",
    "        self.competitor_history.extend(competitor_ads)\n",
    "        if len(self.competitor_history) == 0:\n",
    "            print(\"暂无对手数据\")\n",
    "            return\n",
    "        avg = sum(self.competitor_history) / len(self.competitor_history)\n",
    "        max_ad = max(self.competitor_history)\n",
    "        print(\"\\n对手广告费分析：\")\n",
    "        print(\"  历史平均：\" + str(round(avg, 1)))\n",
    "        print(\"  历史最高：\" + str(max_ad))\n",
    "        print(\"  建议本轮广告费区间：\" + str(round(avg * 0.9, 1)) + \" ~ \" + str(round(avg * 1.2, 1)))\n",
    "\n",
    "    # ===== 功能3：视觉识别截图数据（Qwen3-VL）=====\n",
    "    def extract_from_image(self, image_path: str):\n",
    "        with open(image_path, \"rb\") as f:\n",
    "            img_data = base64.b64encode(f.read()).decode(\"utf-8\")\n",
    "        prompt = \"请提取图中所有订单的产品名、数量、单价，输出为Python字典格式。\"\n",
    "        resp = requests.post(\n",
    "            \"http://localhost:11434/api/generate\",\n",
    "            json={\n",
    "                \"model\": \"qwen3-vl:8b\",\n",
    "                \"prompt\": prompt,\n",
    "                \"images\": [img_data],\n",
    "                \"stream\": False\n",
    "            },\n",
    "            timeout=120\n",
    "        )\n",
    "        result = resp.json()[\"response\"]\n",
    "        print(\"\\n图像识别结果：\")\n",
    "        print(result)\n",
    "        return result\n",
    "\n",
    "    # ===== 功能4：主决策建议（Qwen3）=====\n",
    "    def get_strategic_advice(self, market_info: str):\n",
    "        self.show_status()\n",
    "        seasons_left = self.cash_flow_deadline()\n",
    "\n",
    "        prompt = (\n",
    "            \"你是ERP比赛CEO顾问，给出第\" + str(self.round) + \"轮决策建议。\\n\"\n",
    "            \"财务数据：\" + str(self.data) + \"\\n\"\n",
    "            \"市场信息：\" + market_info + \"\\n\"\n",
    "            \"历史决策：\" + str(self.history[-3:] if self.history else \"暂无\") + \"\\n\"\n",
    "            \"现金流警告：还能撑\" + str(seasons_left) + \"季度\\n\"\n",
    "            \"核心规则：最终以所有者权益高低决定胜负，贷款有利息风险。\\n\\n\"\n",
    "            \"请给出：\\n\"\n",
    "            \"1. 广告费建议金额及理由\\n\"\n",
    "            \"2. 是否贷款，贷多少\\n\"\n",
    "            \"3. 生产线调整建议\\n\"\n",
    "            \"4. 研发投入建议\\n\"\n",
    "            \"5. 本轮最优先事项\"\n",
    "        )\n",
    "\n",
    "        print(\"AI正在分析，请稍候...\")\n",
    "        resp = requests.post(\n",
    "            \"http://localhost:11434/api/generate\",\n",
    "            json={\"model\": \"qwen3:8b\", \"prompt\": prompt, \"stream\": False},\n",
    "            timeout=180\n",
    "        )\n",
    "        advice = resp.json()[\"response\"]\n",
    "        self.history.append({\n",
    "            \"轮次\": self.round,\n",
    "            \"市场\": market_info,\n",
    "            \"权益\": self.data[\"所有者权益\"]\n",
    "        })\n",
    "        self.round += 1\n",
    "        return advice\n",
    "\n",
    "\n",
    "# ========== 启动 ==========\n",
    "my_agent = ERPAgent()\n",
    "\n",
    "# 输入对手上轮广告费（没有就留空列表）\n",
    "my_agent.competitor_analysis([15, 20, 18])\n",
    "\n",
    "# 输入本轮市场信息，运行获取建议\n",
    "market_info = \"本轮市场需求旺盛，竞争对手加大广告投入，原材料价格上涨10%\"\n",
    "advice = my_agent.get_strategic_advice(market_info)\n",
    "print(\"\\nAI建议：\\n\")\n",
    "print(advice)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "e3dc0880-1a67-4188-bff5-f022c63ccf65",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 基于“赛项 A 卷”官方数据的参数初始化\n",
    "params = {\n",
    "    # --- 初始财务状态 ---\n",
    "    \"初始现金\": 100000,           # 现金 100,000\n",
    "    \"初始所有者权益\": 700000,      # 所有者权益合计 700,000\n",
    "    \"原材料价值\": 600000,         # R1-R4 各 300 个，合计 600,000\n",
    "    \n",
    "    # --- 运营硬性规则 ---\n",
    "    \"预算使用率下限\": 0.8,         # 低于 80% 扣 10000 分\n",
    "    \"预算使用率上限\": 1.2,         # 高于 120% 扣 10000 分\n",
    "    \"所得税率\": 0.25,             # 25%\n",
    "    \"违约扣款比例\": 0.40,          # 违约扣 40%\n",
    "    \n",
    "    # --- 费用类 ---\n",
    "    \"每季管理费\": 10000,          # 固定管理费 10,000\n",
    "    \"折旧年限_传统\": 1,            # 传统线 1 年折旧\n",
    "    \"折旧年限_全自动\": 3,          # 全自动 3 年折旧\n",
    "    \n",
    "    # --- 碳中和 ---\n",
    "    \"初始碳排放量\": 100000,        # 100,000 吨\n",
    "    \"碳中和单价\": 20              # 20 元/吨\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "75af9d38-93ed-4d70-8183-2e4acdd53f8d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ 读取成功！\n",
      "数据行数: 63\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import os\n",
    "\n",
    "# 正确获取路径：使用 OneDrive/Desktop\n",
    "desktop = os.path.join(os.path.expanduser('~'), 'OneDrive', 'Desktop')\n",
    "file_name = '经销商订单明细 (1).xls'\n",
    "file_path = os.path.join(desktop, file_name)\n",
    "\n",
    "# 验证文件是否存在\n",
    "if not os.path.exists(file_path):\n",
    "    print(f\"❌ 文件未找到: {file_path}\")\n",
    "else:\n",
    "    # 读取Excel文件\n",
    "    df = pd.read_excel(file_path, engine='xlrd')\n",
    "    print(\"✅ 读取成功！\")\n",
    "    print(f\"数据行数: {len(df)}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "a45dd28b-9d52-4069-9e56-dc6a029953e7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ 读取成功！\n",
      "数据行数：63\n",
      "   年份  季度  编号    市场  产品  特性  供应商参考价格(元)   数量  交货期(季)  账期(季)       认证     估算毛利\n",
      "1   1   2   2  国内市场  P1  T2        1249  471       4      2  ISO9000  -850.92\n",
      "3   1   2   4  国内市场  P1  T3        1130  756       4      4  ISO9000  -960.40\n",
      "2   1   2   3  国内市场  P1  T2        1118  789       3      3  ISO9000  -971.44\n",
      "4   1   2   5  国内市场  P1  T3        1070  756       4      1  ISO9000 -1015.60\n",
      "0   1   2   1  国内市场  P1  T1        1057  588       4      1          -1027.56\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import os\n",
    "\n",
    "# 文件真实路径（根据你提供的位置）\n",
    "file_path = r\"C:\\Users\\Microsoft\\OneDrive\\Desktop\\经销商订单明细 (1).xls\"\n",
    "\n",
    "# 检查文件是否存在\n",
    "if not os.path.exists(file_path):\n",
    "    print(f\"❌ 文件不存在！请检查路径：{file_path}\")\n",
    "else:\n",
    "    # 读取 Excel 的 sheet1\n",
    "    df_orders = pd.read_excel(file_path, sheet_name='sheet1')\n",
    "    print(\"✅ 读取成功！\")\n",
    "    print(f\"数据行数：{len(df_orders)}\")\n",
    "\n",
    "    # 测试函数（根据你的需求调整）\n",
    "    def get_best_order(year, quarter):\n",
    "        current = df_orders[(df_orders['年份'] == year) & (df_orders['季度'] == quarter)].copy()\n",
    "        current['估算毛利'] = current['供应商参考价格(元)'] - 2000 - (current['供应商参考价格(元)'] * 0.08)\n",
    "        return current.sort_values(by='估算毛利', ascending=False).head(5)\n",
    "\n",
    "    # 测试\n",
    "    print(get_best_order(1, 2))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "f24b1127-174f-4a7c-a1df-a03125c97aea",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ 读取成功！\n",
      "数据行数：63\n",
      "   年份  季度  编号    市场  产品  特性  供应商参考价格(元)   数量  交货期(季)  账期(季)       认证     估算毛利\n",
      "1   1   2   2  国内市场  P1  T2        1249  471       4      2  ISO9000  -850.92\n",
      "3   1   2   4  国内市场  P1  T3        1130  756       4      4  ISO9000  -960.40\n",
      "2   1   2   3  国内市场  P1  T2        1118  789       3      3  ISO9000  -971.44\n",
      "4   1   2   5  国内市场  P1  T3        1070  756       4      1  ISO9000 -1015.60\n",
      "0   1   2   1  国内市场  P1  T1        1057  588       4      1          -1027.56\n"
     ]
    }
   ],
   "source": [
    "# 修复后完整代码\n",
    "import pandas as pd\n",
    "import os\n",
    "\n",
    "# 正确获取路径（含 OneDrive）\n",
    "desktop = os.path.join(os.path.expanduser('~'), 'OneDrive', 'Desktop')\n",
    "file_name = \"经销商订单明细 (1).xls\"\n",
    "file_path = os.path.join(desktop, file_name)\n",
    "\n",
    "# 检查文件是否存在\n",
    "if not os.path.exists(file_path):\n",
    "    print(f\"❌ 文件未找到！请检查路径：{file_path}\")\n",
    "else:\n",
    "    # 读取 Excel 文件\n",
    "    df = pd.read_excel(file_path, engine='xlrd')\n",
    "    print(\"✅ 读取成功！\")\n",
    "    print(f\"数据行数：{len(df)}\")\n",
    "\n",
    "    # 测试函数\n",
    "    def get_best_order(year, quarter):\n",
    "        current = df[(df['年份'] == year) & (df['季度'] == quarter)].copy()\n",
    "        current['估算毛利'] = current['供应商参考价格(元)'] - 2000 - (current['供应商参考价格(元)'] * 0.08)\n",
    "        return current.sort_values(by='估算毛利', ascending=False).head(5)\n",
    "\n",
    "    print(get_best_order(1, 2))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "a0dd57d4-752f-4b59-b4d1-23b4a2b9ecb5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🤖 Agent 回复：\n",
      "收到，测试通讯确认。\n"
     ]
    }
   ],
   "source": [
    "import openai\n",
    "\n",
    "# 1. 建立与本地 Ollama 的连接\n",
    "client = openai.OpenAI(\n",
    "    base_url='http://localhost:11434/v1/',  # 注意：最后这个 /v1/ 绝对不能漏掉\n",
    "    api_key='ollama',                       # 随便填，但绝不能是空的\n",
    ")\n",
    "\n",
    "# 2. 呼叫你的 qwen 大脑\n",
    "try:\n",
    "    response = client.chat.completions.create(\n",
    "        model=\"qwen3-vl:8b \",             # 这里的名字必须和你黑框框里的一模一样\n",
    "        messages=[\n",
    "            {\"role\": \"user\", \"content\": \"你好，我是沙盘比赛企业的CEO。测试通讯，收到请用中文回复一句简短的确认。\"}\n",
    "        ]\n",
    "    )\n",
    "    # 3. 打印模型回复\n",
    "    print(\"🤖 Agent 回复：\")\n",
    "    print(response.choices[0].message.content)\n",
    "\n",
    "except Exception as e:\n",
    "    print(f\"❌ 还是报错了，错误信息是：\\n{e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3c420189-40f2-448e-9822-872a8155b350",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
